name: magnet
recipe: drupal9
keys: true
config:
  php: '8.1'
  via: 'apache:2.4'
  database: 'mysql:5.7'
  webroot: web
  drush: ^11
env_file:
  - ./lando/vars.env

services:
  pma:
    type: phpmyadmin
    hosts:
      - database
