christmas_snow: 0
christmas_snow_flakes_max: '128'
christmas_snow_snowcolor: '#FFFFFF'
christmas_snow_flake_bottom: '500'
christmas_snow_follow_mouse: 'false'
christmas_snow_melt: 'true'
christmas_snow_stick: 'false'
christmas_snow_twinkle: 'false'
christmas_snow_character: ·
christmas_snow_animation_int: '50'
christmas_snow_minified: 0
