_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  collapsiblock: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  flood_control: 0
  hacked: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  layout_discovery: 0
  link: 0
  magnet: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pdf_serialization: 0
  phpass: 0
  rest: 0
  search: 0
  search_api: 0
  search_api_db: 0
  search_api_sorts: 0
  serialization: 0
  shortcut: 0
  system: 0
  tablesorter: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  verf: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  xls_serialization: 0
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  stable: 0
  classy: 0
  mapvr: 0
profile: standard
