id_offset: '-11060'
timeframe_drawing: '7'
timeframe_dimpleing: '7'
timeframe_shaping: '7'
timeframe_tunings_and_heat_treatments: '14'
timeframe_gluing: '28'
timeframe_fine_tuning: '7'
timeframe_flexing: '7'
timeframe_nanoing: '0'
timeframe_last_check: '7'
timeframe_packaging: '0'
